/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class verifier_VerifyCertificate */

#ifndef _Included_verifier_VerifyCertificate
#define _Included_verifier_VerifyCertificate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     verifier_VerifyCertificate
 * Method:    verify
 * Signature: ([BJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_verifier_VerifyCertificate_verify
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
